### ISSUE TITLE
Log-automatic, Log-specific, Get-repackfiles

### ISSUE THREAD

**Issue by Cercaj** [improsec/Get-bADpasswords#4]
Hi, do you know why I receve this errors:
Log-Automatic : The term 'Log-Automatic' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
 
Log-Specific : The term 'Log-Specific' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
 
Get-RepackFiles : The term 'Get-RepackFiles' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.

**Comment by st4ckh0und** [comment]
Hello Cercaj, 

These functions are located in the "Helper_Logging.ps1" and "Helper_Passwords.ps1" files, which are loaded relatively by the main script. Please make sure that your current working directory is set to the same directory as the main script when executing, so that the relative pathing to these helper scripts are correct.

You can check this using the following powershell command:
` [System.IO.Directory]::GetCurrentDirectory()`

**Comment by Cercaj** [comment]
> Hello Cercaj,
> 
> These functions are located in the "Helper_Logging.ps1" and "Helper_Passwords.ps1" files, which are loaded relatively by the main script. Please make sure that your current working directory is set to the same directory as the main script when executing, so that the relative pathing to these helper scripts are correct.
> 
> You can check this using the following powershell command:
> ` [System.IO.Directory]::GetCurrentDirectory()`

Hello,
Thank you for you answer, with you message I could find "helrper_password.ps1" was not security assigned, when I assigned all scripts worked fine.
Thank you!
